# 定义函数

## 函数的定义方法

In [ ]:
# def <函数名>(<参数>):
#     """<函数说明>"""
#     <函数代码>
#     <pass>
#     return <返回内容>

格式说明：
* def：定义函数的关键字，所有函数都由它来引导，空格后跟着函数名
* return：函数经过逻辑处理后最终返回的内容，空格后跟着返回值
* pass：如果函数什么都不做，或者部分分支逻辑不干啥，可以用它
* 函数名：函数的名字，看到要大体知道这个函数是干什么的，后边跟着括号()
* 参数：括号内的内容，调用时传入，作为函数代码中的变量，可以为空
* 函数说明：用于说明此函数的作用，参数说明等，可以不写
* 返回内容：函数被调用后最终给出的结果，可以是表达式，也可以是函数代码中的变量

## 实例及说明

In [2]:
def city_tier(city_name):
    """返回一个城市是否一线城市"""
    first_tier = ['北京', '上海', '广州', '深圳']
    if city_name in first_tier:
        return '一线城市'
    else:
        return '非一线城市'

## 函数的调用

In [3]:
# 如果不按要求传参数会报错
# city_tier() # TypeError

# 把调用结果赋值给变量
sh = city_tier('上海')
# sh: '一线城市'
sh = f'上海是{city_tier("上海")}'
print(sh)
# '上海是一线城市'

# 把函数传给变量，然后用此变量调用
ct = city_tier
print(ct('青岛'))
# '非一线城市'

上海是一线城市
非一线城市


如无定义参数不能传入参数：

In [5]:
def me():
    print('我是好人！')


me()  # 我是好人！

我是好人！
Hello World


可选参数的函数

In [9]:
def web(name='盖若'):
    print(f'{name}是个好网站')


web()  # 盖若是个好网站
web('知乎')  # 知乎是个好网站

盖若是个好网站
知乎是个好网站


## 函数返回

In [10]:
type(city_tier('杭州'))  # str
type(web())  # NoneType

盖若是个好网站


NoneType

In [11]:
def circle(r):
    """计算圆的周长和面积"""
    l = 2 * 3.14 * r
    s = 3.14 * (r ** 2)
    return l, s


# 调用
circle(4)  # (25.12, 50.24)

(25.12, 50.24)

# 函数的参数

## 无参数

## 形参和实参
形参：定义时参数名称
实参：实际传入的值
可以理解为一个是变量一个是值，如：

In [12]:
# 定义
def foo(name, age=18, boy=True, **kwargs):
    pass


# 调用
foo('tom', age=20, city='shanghai')

其中，name、age 等是形参，'tom'、20 是实参。

## 默认值参数

In [13]:
foo('小刚')
foo('小刚', 22)
# 也可以给默认参数传值

注：
1. 多个默认值参数如果不指定形参需要按顺序传递变量
2. 如果同时有默认值和没有默认值的参数，没有默认值的必须在有默认值的前边，否则报错

## 位置参数
指在固定位置的参数，在调用时按位置顺序传入

In [16]:
def foo(x, y):
    return x - y


print(foo(10, 8))
print(foo(8, 10))

2
-2


## 关键字参数
调用函数时我们可以使用调用关键字参数，格式为 关键字=参数值，这样就不用关心顺序问题了。

In [17]:
def say(name, age=18, words='hello'):
    print(f'{age}岁的{name}说：{words}')


# 调用
say(name='tom', age=20)  # 20岁的tom说：hello

20岁的tom说：hello


关键字参数后面必须都是关键字参数：

In [19]:
say('tom', age=20)  # 20岁的tom说：hello
# say('tom', age=20, 'good') # 报错

20岁的tom说：hello


## 可变参数
有时候我们不确定参数的数量，可使用可变参数，类似 **kwargs。其中：

* *args 一个星号，以元组(tuple)的形式导入
* **kwargs 两个星号，以字典的形式导入
* args 和 kwargs 是习惯写法，可以用其他变量名称

In [22]:
def foo(*t):
    print(t)


# 调用
foo(1)  # (1,)
foo(1, 4, 5, 6)  # (1, 4, 5, 6)


def foo(**d):
    print(d)


# 调用
foo(a=1)  # {'a': 1}
foo(a=1, b=4, c=5)  # {'a': 1, 'b': 4, 'c': 5}

(1,)
(1, 4, 5, 6)
{'a': 1}
{'a': 1, 'b': 4, 'c': 5}


可变参数与其他类型的参数混用时，采用元组拆包（解包）的原则。

In [21]:
def foo(a, b, *c, d):
    print(a, b, c, d)


# 调用
foo(1, 2, 3, 4, 5, d=6)  # 1 2 (3, 4, 5) 6 d 要用关键字传入

1 2 (3, 4, 5) 6


可以通过 ** 用字典传递关键字参数：

In [23]:
def say(name, age=18, words='hello'):
    print(f'{age}岁的{name}说：{words}')


# 调用
d = {'name': 'tom', 'age': 20, 'words': 'hello'}
say(**d)  # 20岁的tom说：hello

20岁的tom说：hello


## 独立星号
函数的多个参数中间若有一个单独的星号*分隔，则星号后面为命名关键字参数，
星号本身不是参数，会使得函数在调用时必须带参数名字进行调用。如：

In [24]:
def my(x, y, *, name, age):
    print(x, y, name, age)


# 不指定 name 和 age 参数名会报错
# my(1, 2, 'lily', 9)
# TypeError: my() takes 2 positional arguments but 4 were given

# 指定名正常
my(1, 2, name='lily', age=9)
# 1 2 lily 9

1 2 lily 9


## 斜杠参数

In [27]:
# divmod(x, y, /) Return the tuple (x//y, x%y)

# divmod(x=3, y=4)
# TypeError: divmod() takes no keyword arguments
divmod(3, 4)
# (0, 3)

(0, 3)

# 匿名函数 lambda

## 语法结构

In [ ]:
# lambda < 参数 > : < 逻辑表达式代码 >

说明：
* 参数可以一个，可以多个用逗号隔开
* 逻辑代码的计算结果为 lambda 的返回值
* lambda 可以没有参数，同定义无参数的函数一样

## 实例

In [39]:
add = lambda x, y: x + y
add(1, 4)  # 5

5

In [40]:
(lambda x, y: x + y)(3, 5)
# 8

8

## 其他使用

## 条件判断

In [51]:
# 两个数的最大值
(lambda x, y: x if x > y else y)(49, 5)  # 49

49

## 和字典集合

In [50]:
# 可以定义在字典的值里，用 key 来调用
d = {'+': lambda x, y: x + y, '-': lambda x, y: x - y}
d['+'](3, 8)  # 11

11

## map

In [49]:
# 作为 map 的迭代方法
a = [1, 2, 3, 4, 5, 6]
result = map(lambda x: x + 1, a)
list(result)
# [2, 3, 4, 5, 6, 7]

[2, 3, 4, 5, 6, 7]

## filter

In [48]:
# 作为过虑器的过滤逻辑
a = [1, 2, 3, 4, 5, 6]
result = filter(lambda x: x % 2 == 0, a)
list(result)

[2, 4, 6]

## reduce

In [47]:
from functools import reduce

# 作为 reduce 累积迭代的方法
a = [1, 2, 3, 4, 5, 6]
result = reduce(lambda x, y: x + y, a)
result
# 21

21

## sorted

In [44]:
# 指定属性排序
s = [{'name': 'tom', 'age': 22},
     {'name': 'lily', 'age': 19},
     {'name': 'lucy', 'age': 20}]

sorted(s, key=lambda x: x['age'])

# [{'name': 'lily', 'age': 19},
#  {'name': 'lucy', 'age': 20},
#  {'name': 'tom', 'age': 22}]

[{'name': 'lily', 'age': 19},
 {'name': 'lucy', 'age': 20},
 {'name': 'tom', 'age': 22}]

## iter
iter() 函数生成迭代器，lambda 中可用 next() 调用：

In [53]:
# # 注：x 变量没有用，在一些对象中可用来占位
# n = lambda x, y=iter('abcdef'): next(y)
# # 可调用 6 次，每次返回其中一个值
# n()  # 'a'
# n()  # 'b'

# 装饰器

## 讲解

In [29]:
def foo(x):
    print('foo out:', x)


# 调用函数
foo(123)
# foo out: 123

foo out: 123


需求是给上面的函数加上执行日志，下面写出函数逻辑：

In [34]:
def log(func):
    def decorator(*args, **kwargs):
        print(f'开始执行: {func.__name__}')
        func(*args, **kwargs)
        print('执行结束')

    return decorator

给 foo 函数应用装饰器：

In [37]:
@log
def foo(x):
    print('foo out:', x)


foo('Hello World')

开始执行: foo
foo out: Hello World
执行结束


## 应用场景
权限校验、用户认证、事务处理、日志记录、性能测试、缓存

## 类装饰器

## 内置装饰器
* @property：把函数装饰成属性
* @staticmethod：不需要实例化，直接可以调用类中的方法
* @classmethod：用来为一个类创建一些预处理的实例

# 内置函数

# 高阶函数

## 特点
 * 函数是对象类型（Object type）的实例
 * 可以将函数存储在变量中
 * 可以将函数作为参数传递给另一个函数
 * 可以从函数返回哈数
 * 可以将函数存储在数据结构中，如哈希表、列表等

## 函数作为对象

In [62]:
def shout(text):
    return text.upper()


print(shout('Hello'))
# Hello

# 将函数赋值给变量
yell = shout

print(yell('hello'))
# Hello

HELLO
HELLO


在这里我们创建了一个函数 greet，它将函数作为参数

In [63]:
def shout(text):
    return text.upper()


def whisper(text):
    return text.lower()


def greet(func):
    # 将函数存储在变量中
    greeting = func("Hi, I am created by a function \
    passed as an argument.")
    print(greeting)


greet(shout)
# HI, I AM CREATED BY A FUNCTION PASSED AS AN ARGUMENT.
greet(whisper)
# hi, i am created by a function passed as an argument.

HI, I AM CREATED BY A FUNCTION     PASSED AS AN ARGUMENT.
hi, i am created by a function     passed as an argument.


## 返回函数
由于函数是对象，我们也可以从另一个函数返回一个函数。在下面的示例中，create_adder 函数返回 adder 函数

In [64]:
# 来说明函数可以返回另一个函数
def create_adder(x):
    def adder(y):
        return x + y

    return adder


add_15 = create_adder(15)

print(add_15(10))
# 25

25


## 装饰器
装饰器是 Python 中最常用的高阶函数。它允许程序员修改函数或类的行为。装饰器允许我们包装另一个函数，以扩展包装函数的行为，而无需永久修改它。在 Decorators 中，函数作为参数被放入另一个函数中，然后在包装器函数中调用。

In [66]:
# @gfg_decorator
# def hello_decorator():
#     ...
#
# # 上述代码相当于：
#
# def hello_decorator():
#     ...
#
# hello_decorator = gfg_decorator(hello_decorator)

In [99]:
from time import sleep, time


def run_time(func):
    def wrapper():
        start = time()
        func()  # 函数在这里运行
        end = time()
        cost_time = end - start
        print("func three run time {}".format(cost_time))

    return wrapper


@run_time
def fun_one():
    sleep(1)


@run_time
def fun_two():
    sleep(1)


@run_time
def fun_three():
    sleep(1)


fun_one()
fun_two()
fun_three()

func three run time 1.0110828876495361


In [102]:
def test(func):
    def wrapper():
        print("Hello before")
        func()
        print("Hello after")

    return wrapper


@test
def hello():
    print("test")


hello()

Hello before
test
Hello after


# map()

## 语法
map(function, iterable, ...)
参数说明：
* function - 对可迭代的元素依次应用这个函数（可调用对象），函数的传入值是每个元素
* iterable - 要映射的可迭代对象，可以是多个序列
可以向 map 函数传递多个 iterable，对应的函数也要接受相同序列数量的参数

## 返回
返回一个将 function 应用于 iterable 中每一项并输出其结果的迭代器

## 案例
### 单个可迭代对象

In [1]:
# 单个对象
def add_1(x):
    return x + 1


m = map(add_1, [1, 2, 3, 4])
list(m)
# [2, 3, 4, 5]

[2, 3, 4, 5]

### 多个可迭代对象

In [ ]:
# 多个对象
def add_num(x, y):
    return x + y


m = map(add_num, [1, 2, 3, 4], [1, 2, 3, 4])
list(m)

多个序列如果长度不一样，只会处理到最短的元素位置：

In [3]:
# 对象不同长度
def add_num(x, y):
    return x + y


m = map(add_num, [1, 2, 3, 4], [1, 2])
list(m)

[2, 4]

有几个序列，函数就要承接几个参数：

In [6]:
# 多个对象
def add_num(x, y, z):
    return x + y + z


a = [1, 2, 3]
m = map(add_num, a, a, a)
list(m)

[3, 6, 9]

### 使用匿名函数

In [7]:
m = map(lambda x, y: x + y, [1, 2, 3, 4], [1, 2])
list(m)

[2, 4]

## 其他
对于函数的输入已经是参数元组的情况，可以使用 itertools.starmap() 操作

In [8]:
import itertools

t = [(2, 5), (3, 4)]
# 元组内操作（相乘）
sm = itertools.starmap(lambda x, y: x * y, t)
list(sm)

[10, 12]

## 列表表达式

In [11]:
l = [-2, -1, 0]
print([abs(x) for x in l])
# [2, 1, 0]

print([x ** 2 for x in l])
# [4, 1, 0]

l_1 = [1, 2, 3]
l_2 = [10, 20, 30]
print([x * y for x, y in zip(l_1, l_2)])
# [10, 40, 90]

[2, 1, 0]
[4, 1, 0]
[10, 40, 90]


## Numpy

In [12]:
import numpy as np

a = np.array([-2, -1, 0])
print(np.abs(a))
# [2 1 0]

print(a ** 2)
# [4 1 0]

a_1 = np.array([1, 2, 3])
a_2 = np.array([10, 20, 30])
print(a_1 * a_2)
# [10 40 90]

[2 1 0]
[4 1 0]
[10 40 90]


# filter()

## 语法
filter(function, iterable)
参数：
* function - 测试 iterable 元素是否返回 true 或 false 的函数
* iterable - 要过滤的iterable，可以是集合、列表、元组或任何迭代器的容器

## 返回
filter() 方法返回一个迭代器（filter对象），该迭代器通过 iterable 中每个元素的函数检查，返回的是原序列中的值，非布尔值

## filter 对象
以值为偶数时返回 True 的 lambda 函数为例：

In [18]:
l = [-2, -1, 0, 1, 2]
print(filter(lambda x: x % 2 == 0, l))

print(type(filter(lambda x: x % 2 == 0, l)))

for i in filter(lambda x: x % 2 == 0, l):
    print(i)

<class 'filter'>
-2
0
2


## 案例

In [20]:
# 筛选大于 5 的值
f = filter(lambda x: x > 5, [2, 3, 5, 7, 9])
f  # <filter at 0x7fe33ea36730>
print(list(f))
# [7, 9]

# 函数为 None
f = filter(None, [2, False, 5, None, 9])
list(f)
# [2, 5, 9]

[7, 9]


[2, 5, 9]

In [21]:
# list of letters
letters = ['a', 'b', 'd', 'e', 'i', 'j', 'o']


# function that filters vowels
def filter_vowels(letter):
    vowels = ['a', 'e', 'i', 'o', 'u']

    if letter in vowels:
        return True
    else:
        return False


filtered_vowels = filter(filter_vowels, letters)

print('The filtered vowels are:')
for vowel in filtered_vowels:
    print(vowel)
'''
The filtered vowels are:
a
e
i
o
'''

The filtered vowels are:
a
e
i
o


'\nThe filtered vowels are:\na\ne\ni\no\n'

## 列表表达式

In [27]:
l = [-2, -1, 0, 1, 2]
print([x for x in l if x % 2 == 0])
# [-2, 0, 2]

print([x for x in l if x % 2 != 0])
# [-1, 1]

l_s = ['apple', 'orange', 'strawberry']
print([x for x in l_s if x.endswith('e')])
# ['apple', 'orange']

print([x for x in l_s if not x.endswith('e')])
# ['strawberry']

l = [-2, -1, 0, 1, 2]
print([x for x in l if x])
# [-2, -1, 1, 2]

l_2d = [[0, 1, 2], [], [3, 4, 5]]
print([x for x in l_2d if x])
# [[0, 1, 2], [3, 4, 5]]

[-2, 0, 2]
[-1, 1]
['apple', 'orange']
['strawberry']
[-2, -1, 1, 2]
[[0, 1, 2], [3, 4, 5]]


## 其他

了解 itertools.filterfalse()，只有function返回 false 时才选取 iterable 中元素的补充函数

# zip()
## 简单理解
常用于将两个及以上的列表（可迭代对象）按位置一一对应地拉在一起。

## 语法参数
zip(*iterables)
参数 iterables 可以是一个内置的迭代对象（list，dict等）或是用户自定义的可迭代对象

## 函数返回
根据传入参数的情况，返回的内容分别为：
* 不传递任何参数，将返回一个空迭代器（zip 对象）
* 传递一个可迭代对象，返回一个元组迭代器，每个元组只有一个元素
* 传递多个可迭代对象，返回一个元组迭代器，每个元组都包含来自所有 iterables 的元素，迭代器在最短 iterable 耗尽时停止
针对第三种情况，如一个包含 2 个元素，另一个包含 3 个元素，则返回的迭代器将包含 2 个元组，每个元组以第一个元组的 2 个元素开头，传入的第二个元组的最后一个数据被丢弃

## 示例

In [35]:
# 无传入
z = zip()
print(z)
# <zip at 0x7fe33d1ac440>
print(list(z))
# []

# 传入一个
z = zip([1, 2, 3])
print(list(z))
# [(1,), (2,), (3,)]

# 传入两个
z = zip([1, 2, 3], [3, 4, 5])
print(list(z))
# [(1, 3), (2, 4), (3, 5)]

# 不同长度
z = zip([1, 2], [3, 4, 5])
print(list(z))
# [(1, 3), (2, 4)]

z = zip([1, 2, 3], [4, 5])
print(list(z))
# [(1, 4), (2, 5)]

# 解包
coordinate = ['x', 'y', 'z']
value = [3, 4, 5]

result = zip(coordinate, value)
result_list = list(result)
print(result_list)
# [('x', 3), ('y', 4), ('z', 5)]

c, v = zip(*result_list)
print(c)
# ('x', 'y', 'z')
print(v)
# (3, 4, 5)

[]
[(1,), (2,), (3,)]
[(1, 3), (2, 4), (3, 5)]
[(1, 3), (2, 4)]
[(1, 4), (2, 5)]
[('x', 3), ('y', 4), ('z', 5)]
('x', 'y', 'z')
(3, 4, 5)


## zip 对象的应用

In [30]:
# 分别是每个人的 身高、体重、年龄
lily = [168, 50, 22]
lucy = [170, 55, 25]
amy = [175, 53, 24]

In [31]:
z = zip(lily, lucy, amy)
list(z)
# [(168, 170, 175), (50, 55, 53), (22, 25, 24)]

[(168, 170, 175), (50, 55, 53), (22, 25, 24)]

In [32]:
z = zip(lily, lucy, amy)
h = list(z)[0]
sum(h) / 3
# 171.0

171.0

其他案例：

In [33]:
names = ['Alice', 'Bob', 'Charlie']
ages = [24, 50, 18]

for name, age in zip(names, ages):
    print(name, age)
# Alice 24
# Bob 50
# Charlie 18

Alice 24
Bob 50
Charlie 18


## 短板补齐
如果传入的多个可迭代对象的长度不等，则取最短的对应
如果想按最长的处理，不足的用 None 补齐，则可以使用 itertools 中的 zip_longest 方法

In [29]:
import itertools

z = itertools.zip_longest([1, 2], [3, 4, 5])
list(z)

[(1, 3), (2, 4), (None, 5)]

# reduce()

## 理解reduce
**reduce(function, iterable[, initializer])**

function 第一次执行时，按顺序先取两个传入执行，得到一个结果，然后再将这个结果与 iterable 中的下一个值（还是两个变量）传入 function 执行，如此反复直到 iterable 里的值取完为止，最终就能得到一个终极的返回值

## 案例

In [37]:
from functools import reduce

reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

### 累积数据操作

In [42]:
from functools import reduce
from operator import truediv

print(reduce(truediv, [4, 3, 2, 1]))
reduce(lambda x, y: x / y, [4, 3, 2, 1])

0.6666666666666666


0.6666666666666666

### initializer 参数
指定 initializer 参数时，第一次执行时，函数的第一个参数传入此值，第二个参数为序列的第一个值：

In [47]:
from functools import reduce
from operator import truediv

print(reduce(truediv, [10, 5, 2], 50))
# 0.5
print(reduce(truediv, [], 50))
# 50
# reduce(truediv, [])
# TypeError: reduce() of empty iterable with no initial value
print(reduce(truediv, [10]))
# 10

0.5
50
10


### pandas 合并数据

In [49]:
# reduce(lambda a, b: pd.merge(a, b, on=['ID']), dflist)